### ISSUE TITLE
Bug: Running a command with `-` in the name presents an error message that it was not found

### ISSUE THREAD

**Issue by tminusplus** [XaF/omni#45]
If you define a command with `-` in it, like `ko-build`, it will let you run the command as `omni ko-build` but presents an error that the command was not found before doing so.

I was expecting that since the command is defined as `ko-build` it would alias over to `ko build`.

Omni config: https://github.com/tminusplus/caddy-tailscale/blob/ts/.omni.yaml
Example:
```
~/git/tminusplus/caddy-tailscale ts
❯ omni help
omni - omnipotent tool (v0.0.12)

Usage: omni <command> [options] ARG...

General
  help               Show help for omni commands
  hook               Call one of omni's hooks for the shell.
  status             Show the status of omni

Git commands
  cd                 Change directory to the git directory of the specified repository
  clone              Clone the specified repository
  scope              Runs an omni command in the context of the specified repository
  tidy               Organize your git repositories using the configured format
  up, down           Sets up or tear down a repository depending on its up configuration

Build < Configuration < .omni.yaml
  ko build           Build a Caddy container image with the tailscale module.

~/git/tminusplus/caddy-tailscale ts
❯ omni ko build
Error: error creating publisher: KO_DOCKER_REPO environment variable is unset

~/git/tminusplus/caddy-tailscale ts
❯ omni ko-build
omni: command not found: ko-build
omni: found: ko build
Error: error creating publisher: KO_DOCKER_REPO environment variable is unset
```

**Comment by XaF** [comment]
So actually not a bug... but a feature :o)

When a command is not found, omni will generally show you the list of close commands with a "did you mean" suggestion.
When the fuzzy-identified commands are close enough (see `command_match_skip_prompt_if` in the parameters, [details here](https://omnicli.dev/reference/configuration/parameters/skip-prompt-if)), omni will skip asking `Did you mean` and simply run the command for you. This is why you're seeing `omni: found: ko build` in your second call!

You can reconfigure or entirely disable that by changing the values of the `command_match_skip_prompt_if` in your configuration. Omni's just trying to be helpful :D

**Comment by tminusplus** [comment]
Omni is being helpful here, but since it already aliased `ko-build` to `ko build` I think it should be able to pick-up that `ko-build` is `ko build` without reporting the `command not found` error.

More complexity, but it makes it inconsistent that it will auto split on dash but not understand the originally defined command.

**Comment by XaF** [comment]
It's not that it does not understand it, it's that the command is being replaced, not aliased!
Split on dash does not create aliases, and after parsing the command omni has no knowledge of the original command before split. that's to avoid having a bloated help message with all the commands pre-split and post-split.

`ko-build` is not being aliased, it's just the fuzzy match that considers it's close enough that it just runs it for you
