### ISSUE TITLE
Fish shell integration uses an absolute path for $HOME

### ISSUE THREAD

**Issue by tminusplus** [XaF/omni#7]
Noticed that the Fish shell integration uses an absolute path, instead of a variable, to refer to the home directory:
```
❯ cat ~/.config/fish/conf.d/omni.fish
test -f "/Users/tszucs/git/XaF/omni/shell_integration/omni.fish"; and source "/Users/tszucs/git/XaF/omni/shell_integration/omni.fish"
```

This means that syncing my fish config to another computer (ex. Mac -> Linux) will break the fish config, if the home directory or user is different. I did not check the other shell integrations.

**Comment by XaF** [comment]
I think you are still using the old integration which provided the full file. New integration should be as simple as:

```
omni hook init fish | source
```

Anywhere in your fish configuration.
Am I missing something else?

**Comment by tminusplus** [comment]
That is right, it was a leftover from the Ruby version's install.
